### ISSUE TITLE
Issue regarding IntervalManagedBySet

### ISSUE THREAD

**Issue by OnjoujiToki** [emthrm/cp-library#3]
Thanks for your amazing work, emthrm san!
I learned a lot from your implementation for a lot of data structures and algo.
I noticed a bug in your implementation of IntervalManagedBySet. It is happening in erase[left, right]
```C++
IntervalManagedBySet<int> s;
  s.insert(10, 20);
  s.erase(16,17);
  std::cout << s << '\n';
```
supposed to output
```
[10,15] [18, 20]
```
instead, it gives output of 
```C++
[10, 15]
```

Thanks for taking time reading this.
Appreciate your great coding style and super readable codes.

**Comment by emthrm** [comment]
Sorry I did not notice your valuable comment.
I will fix this bug ASAP.

**Comment by emthrm** [comment]
@OnjoujiToki Thank you for reporting this issue!

**Comment by OnjoujiToki** [comment]
Love your work<3
